name: Release Pipeline


on:
  push:
    branches:
      - main
      - next
      - '[0-9]+.x'        # Matches 1.x, 1.x, etc.
      - '[0-9]+.[0-9]+.x' # Matches 1.2.x, 1.1.x, etc.

permissions:
  id-token: write # Required for OIDC
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --include=dev --include=optional --no-audit --prefer-offline

      - name: Audit
        run: |
          npm audit --omit dev
          npm audit signatures
        continue-on-error: true

      - name: Lint and Format
        run: |
          npm run lint
          npm run format

      - name: Tests
        run: |
          npm run test
          npm run e2e:ci

      - name: Build
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: npx semantic-release
